language: python
os:
  - linux
env:
  global:
    - PIP_CACHE_DIR="$HOME/.cache/pip"
    - CODECOV_TOKEN="2968f481-26fd-4375-89d3-44424b7bbdb1"
cache:
  pip: true
  directories:
    - $HOME/.cache/pip
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log
notifications:
  email: false
python:
  - "3.6"
  - "3.7"
  - "3.8"
  # - "3.9-dev"
install:
  - python setup.py install
  - pip install pytest coverage codecov
script:
  - coverage run --source=scripter -m pytest
after_script:
  - codecov
branches:
  only:
    - master
  